feat: scripts to install or update uosc with a single line
tomasklaen/uosc pull request #691
Opened 2023-10-10 21:29 UTC by tomasklaen

I haven't tested the script for Linux & macOS. If anyone could, it'd be nice :) It should install current latest stable.

I also want to figure out if we can provide a `uosc/update` command that people can just run from their menu and update uosc in the background.

2023-10-10 23:51 UTC, christoph-heinrich commented
Github redirects the download url and curl can't deal with that without adding `-L`, and `~` needs to be expanded manually.
```diff
diff --git a/installers/unix.sh b/installers/unix.sh
index 8d30e88..97872a0 100644
--- a/installers/unix.sh
+++ b/installers/unix.sh
@@ -29,6 +29,8 @@ else
 	abort "This install script works only on linux and macOS."
 fi
 
+data_dir="${data_dir/#\~/$HOME}"
+
 # Remove old and deprecated folders & files
 echo "Deleting old and deprecated uosc files and directories."
 rm -rf "$data_dir/scripts/uosc_shared"
@@ -37,7 +39,7 @@ rm -f "$data_dir/scripts/uosc.lua"
 
 # Install new version
 echo "Downloading: $zip_url"
-curl -o $zip_file $zip_url
+curl -L -o $zip_file $zip_url
 echo "Extracting: $zip_file"
 unzip -od $data_dir $zip_file
 cleanup
@@ -49,7 +51,7 @@ if [ ! -f "$conf_file" ]; then
 	echo "Config not found."
 	mkdir -pv $scriptopts_dir
 	echo "Downloading: $conf_url"
-	curl -o $conf_file $conf_url
+	curl -L -o $conf_file $conf_url
 fi
 
 echo "uosc has been installed."
```

2023-10-11 00:47 UTC, christoph-heinrich requested changes
Can't test on mac, but this is required for linux.

2023-10-11 00:47 UTC, christoph-heinrich commented on installers/unix.sh
> +	data_dir="${XDG_CONFIG_HOME:-~/.config}/mpv"
```suggestion
	data_dir="${XDG_CONFIG_HOME:-$HOME/.config}/mpv"
```
`~` doesn't get automatically expanded

2023-10-11 00:47 UTC, christoph-heinrich commented on installers/unix.sh
> +curl -o $zip_file $zip_url
```suggestion
curl -L -o $zip_file $zip_url
```
curl doesn't deal with the redirect unless `-L` is passed

2023-10-11 00:47 UTC, christoph-heinrich commented on installers/unix.sh
> +	curl -o $conf_file $conf_url
same as above

2023-10-12 07:04 UTC, tomasklaen commented
Is there no way in mpv to spawn an async subprocess that won't freeze the UI and listen to its stdout and exit events with callbacks?

2023-10-12 15:57 UTC, tomasklaen commented
I completely missed that 😐.

2023-10-12 16:00 UTC, merged

2023-10-12 16:27 UTC, christoph-heinrich commented
I think it's possible to start a process directly from lua and then treat it's stdin and stdout like a file, but I never tried that myself.

2023-10-14 08:03 UTC, tomasklaen commented
> I think it's possible to start a process directly from lua and then treat it's stdin and stdout like a file, but I never tried that myself.

What do you mean by this? Make the process output into a file with `command > file.txt` and read the file periodically?

2023-10-14 18:28 UTC, christoph-heinrich commented
> What do you mean by this?

https://www.lua.org/manual/5.1/manual.html#pdf-io.popen

2023-10-14 21:14 UTC, tomasklaen commented
Dunno why I always assume we don't have access to stuff like this in here. But I can't find any docs, or snippets on how to use it asynchronously without blocking the thread.